// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Microsoft.Crm.Services.Utility")]
[assembly: AssemblyProductAttribute("DynamicsCRMProvider")]
[assembly: AssemblyDescriptionAttribute("A type provider for Microsoft Dynamics CRM 2011.")]
[assembly: AssemblyVersionAttribute("0.2.1")]
[assembly: AssemblyFileVersionAttribute("0.2.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.2.1";
    }
}
