// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("DynamicsCRMProvider")>]
[<assembly: AssemblyProductAttribute("DynamicsCRMProvider")>]
[<assembly: AssemblyDescriptionAttribute("A type provider for Microsoft Dynamics CRM 2011.")>]
[<assembly: AssemblyVersionAttribute("0.2.1")>]
[<assembly: AssemblyFileVersionAttribute("0.2.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "DynamicsCRMProvider"
    let [<Literal>] AssemblyProduct = "DynamicsCRMProvider"
    let [<Literal>] AssemblyDescription = "A type provider for Microsoft Dynamics CRM 2011."
    let [<Literal>] AssemblyVersion = "0.2.1"
    let [<Literal>] AssemblyFileVersion = "0.2.1"
