// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("DynamicsCRMProvider")>]
[<assembly: AssemblyProductAttribute("DynamicsCRMProvider365")>]
[<assembly: AssemblyDescriptionAttribute("A type provider for Microsoft Dynamics CRM 365.")>]
[<assembly: AssemblyVersionAttribute("0.3.0")>]
[<assembly: AssemblyFileVersionAttribute("0.3.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "DynamicsCRMProvider"
    let [<Literal>] AssemblyProduct = "DynamicsCRMProvider365"
    let [<Literal>] AssemblyDescription = "A type provider for Microsoft Dynamics CRM 365."
    let [<Literal>] AssemblyVersion = "0.3.0"
    let [<Literal>] AssemblyFileVersion = "0.3.0"
